<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17101" started-at="2022-05-25T01:45:04 BDT" finished-at="2022-05-25T01:45:21 BDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17101" started-at="2022-05-25T01:45:04 BDT" finished-at="2022-05-25T01:45:21 BDT">
      <class name="testCasePackage.TC002_VarifyPageTitle">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCasePackage.TC002_VarifyPageTitle@545997b1]" name="setup" is-config="true" duration-ms="6111" started-at="2022-05-25T01:44:58 BDT" finished-at="2022-05-25T01:45:04 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="VarifyPageTitle()[pri:0, instance:testCasePackage.TC002_VarifyPageTitle@545997b1]" name="VarifyPageTitle" duration-ms="17054" started-at="2022-05-25T01:45:04 BDT" finished-at="2022-05-25T01:45:21 BDT">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at pageObjectPackage.PO_002_VarifyPageTitle.<init>(PO_002_VarifyPageTitle.java:15)
at testCasePackage.TC002_VarifyPageTitle.VarifyPageTitle(TC002_VarifyPageTitle.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VarifyPageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCasePackage.TC002_VarifyPageTitle@545997b1]" name="tearDown" is-config="true" duration-ms="1107" started-at="2022-05-25T01:45:21 BDT" finished-at="2022-05-25T01:45:22 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCasePackage.TC002_VarifyPageTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
